### PR TITLE
Add signal tags

### PR DESCRIPTION
**Pull request by grabanal**
In `config/file_list.json`:
- Add separate VVZ signal processes 
- Add signal VH processes

In `src/analysis_utils.jl`:
- Add separate signal tags 

This is admittedly not a very efficient way of doing this, but signal samples are small.

### CODE REVIEW

**Comment by grabanal** [comment]
One last thing to be implemented is to create background VH samples. But I haven't figured out a good way to do this yet.

**Comment by Moelf** [comment]
is that basically: https://github.com/Moelf/WVZAnalysis.jl/pull/124/files ?

**Comment by grabanal** [comment]
Oops, yes it's basically similar. I only looked at the branches. I missed that PR

**Comment by grabanal** [comment]
Closing because redundance

**Pull request closed without merging**
